### ISSUE TITLE
Assessment Results

### ISSUE THREAD

**Issue by francepack** [kevinhartmann23/mod_0_skills#1]
@kevinhartmann23 
Overall, nice work here! You've performed well enough on this assessment to merit making some changes to achieve being `technical ready`. Please make the following updates by EOD Sunday:

- [ ] I think your first class concept could be a bit more clear. I am not sure what `POS System` is... frankly, my head goes to `piece of...`, well, let's just say it doesn't make these establishments seem that quality hah! So I think a stronger class name will help you refine your class idea. What I see with your attributes is that perhaps you are taking on too much. Perhaps try to distinguish between if you want to represent different restaurants with each instance, or if you want to represent parties, or perhaps even a menu... All that said, you have some solid attribute/method relationships here- just struggling to see what is in the scope of an instance of that particular class.

- [ ] I am seeing your second class more holistically- I think all those methods and attributes work very well. A couple method names to look at: `burntFood` doesn't quite follow the general naming pattern of a method- it is best to keep these present tense when possible, so just taking a particular letter of that method name will help it read better. `missingIngredient` also does not begin with the kind of present, active word we try to get to start method names. Perhaps a word like `forget` or `lose`, or something similar will work here.

**Comment by kevinhartmann23** [comment]
@francepack 

I completely agree, I got a little caught up in technical aspects of restaurants. I was over thinking it! `POS systems` stands for `Point Of Sale System` although most of the time they do operate like a `piece of ----`! I have trouble finding actual calls examples and not taking things to literally. 

I will have these fixed by EOD sunday! 

Thanks.

**Comment by kevinhartmann23** [comment]
@francepack 

Alright, everything has been updated! 

Thank you for the feedback!
